-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2017.4 Schlumberger
-- User name   : Aqnan Matthew
-- Date        : Tuesday, April 13 2021 22:33:26
-- Project     : EggModel.pet
-- Generated ]

-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2017.4 Schlumberger
-- User name   : Aqnan Matthew
-- Date        : Thursday, April 15 2021 15:30:09
-- Project     : Gullfaks_new_tuned.pet
-- Generated ]

RUNSUM

FCMPR                                  -- Generated : Petrel
 /

WCMPR                                  -- Generated : Petrel
'*' 1 /
'*' 2 /
'*' 3 /
'*' 4 /
'*' 5 /
'*' 6 /
'*' 7 /
/

FCMPT                                  -- Generated : Petrel
 /

--WCMPT                                  -- Generated : Petrel
--'*' 1 /
--'*' 2 /
--'*' 3 /
--'*' 4 /
--'*' 5 /
--'*' 6 /
--'*' 7 /
--/

WSTAT                                  -- Generated : Petrel
 /

WWGR                                   -- Generated : Petrel
 /

WWCT                                   -- Generated : Petrel
 /

WTHP                                   -- Generated : Petrel
 /

TIMESTEP                               -- Generated : Petrel

--FVPR                                   -- Generated : Petrel

WVPR                                   -- Generated : Petrel
 /

--FVPT                                   -- Generated : Petrel

WVPT                                   -- Generated : Petrel
 /

--FVIR                                   -- Generated : Petrel

WVIR                                   -- Generated : Petrel
 /

--FVIT                                   -- Generated : Petrel

WVIT                                   -- Generated : Petrel
 /

WPI                                    -- Generated : Petrel
 /

FWPR                                   -- Generated : Petrel

WWPR                                   -- Generated : Petrel
 /

FOPR                                   -- Generated : Petrel

WOPR                                   -- Generated : Petrel
 /

FGPR                                   -- Generated : Petrel

WGPR                                   -- Generated : Petrel
 /

WEPR                                   -- Generated : Petrel
 /

FWPT                                   -- Generated : Petrel

WWPT                                   -- Generated : Petrel
 /

FOPT                                   -- Generated : Petrel

WOPT                                   -- Generated : Petrel
 /

FGPT                                   -- Generated : Petrel

WGPT                                   -- Generated : Petrel
 /

FPR                                    -- Generated : Petrel

FWIP                                   -- Generated : Petrel

--FOIPG                                  -- Generated : Petrel

--FGIPL                                  -- Generated : Petrel

FOIP                                   -- Generated : Petrel

--FOIPL                                  -- Generated : Petrel

FGIP                                   -- Generated : Petrel

--FGIPG                                  -- Generated : Petrel

--FGIPR

--FGSAT

FWIR                                   -- Generated : Petrel

WWIR                                   -- Generated : Petrel
 /

WOIR                                   -- Generated : Petrel
 /

FGIR                                   -- Generated : Petrel

WGIR                                   -- Generated : Petrel
 /

FWIT                                   -- Generated : Petrel

WWIT                                   -- Generated : Petrel
 /

WOIT                                   -- Generated : Petrel
 /

FGIT                                   -- Generated : Petrel

WGIT                                   -- Generated : Petrel
 /

FGOR                                   -- Generated : Petrel

WGOR                                   -- Generated : Petrel
 /

WBHP                                   -- Generated : Petrel
 /

--CO2 dissolved in water phase
--FWCD
--CO2 trapped (immobile) in gas phase
--FGCDI
--CO2 mobile in gas phase
--FGCDM
--Hydrocarbon Component Molar Injection Totals
--FCMIT
--Component Hydrocarbon as Moles
--FCMIP
--Molar amount of specified component mobile in gas
FCGMM
 /
--Molar amount of specified component trapped in gas
FCGMI
 /
--Molar amount of specified dissolved in water
FCWM
 /

RPTONLY                                -- Generated : Petrel



