-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2017.4 Schlumberger
-- User name   : Aqnan Matthew
-- Date        : Tuesday, April 13 2021 22:33:26
-- Project     : EggModel.pet
-- Generated ]

INIT                                   -- Generated : Petrel

GRIDFILE                               -- Generated : Petrel
  0 1 /

GRIDUNIT                               -- Generated : Petrel
  METRES /

MAPUNITS                               -- Generated : Petrel
  METRES /

MAPAXES                                -- Generated : Petrel
  0 -999 0 1 1000 1 /

